<a href="https://colab.research.google.com/github/josedalvik/datascience_python1_tarea6/blob/main/Tarea_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 7

Ejercicio: Investigar y ejemplificar diferencias entre np.array y np.matrix

In [2]:
# Diferencias entre np.array y np.matrix

import numpy as np

print("Las matrices son bidimencionales:")
m = np.matrix([[1, 2], [3, 4]])
print(m)

print("Las matrices son subtipo de los array, es decir heredan sus funciones.")
print(m.shape)

print("La matriz como tal tiene la función de obtener su inversa, utilizando notación simple.")
print(m.I)

print("Los arrays son vectores n-dimensionales, utilizan funciones más generales.")
r = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print(r)
print(r.ndim)
print(r.shape)

print("Los arrays soportan operaciones n-dimensionales algebraicas")
r2 = r*2
print(r2)

print("Los arrays son el estandar de vectores o tensores utilizados por numpy.")
print(np.dot(r, r2))

Las matrices son bidimencionales:
[[1 2]
 [3 4]]
Las matrices son subtipo de los array, es decir heredan sus funciones.
(2, 2)
La matriz como tal tiene la función de obtener su inversa, utilizando notación simple.
[[-2.   1. ]
 [ 1.5 -0.5]]
Los arrays son vectores n-dimensionales, utilizan funciones más generales.
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
Los arrays soportan operaciones n-dimensionales algebraicas
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]
Los arrays son el estandar de vectores o tensores utilizados por numpy.
[[[[ 14  20]
   [ 38  44]]

  [[ 30  44]
   [ 86 100]]]


 [[[ 46  68]
   [134 156]]

  [[ 62  92]
   [182 212]]]]


# Clase 8

# New Section

**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresión.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = número de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [3]:
#Ejercicio 

import numpy as np
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

Vs = R + ( gamma * P * V )
print(Vs)

[[10.  2.  5.]
 [10.  2.  5.]
 [10.  2.  5.]]


**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [5]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1


print(OL)

[[0.99995577]
 [0.99999332]]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [6]:
import numpy as np

X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

def ReLu(x):
  return np.piecewise(x, [x < 0, x >= 0], [ lambda x:0, lambda x: x ])

def neural_network(x, funcion_de_activacion):
  H_W = np.array([[0.712, 0.355, 0.268], [0.112, 0.855, 0.468]])
  OL_W = np.array([[0.116], [0.329], [0.708]])

  H1 = np.matmul(x, H_W)
  H1 = funcion_de_activacion(H1)

  OL = np.matmul(H1, OL_W)
  OL = funcion_de_activacion(OL)

  return OL

a =  np.array([[1, 1]])
print("Prueba inicial: ", neural_network(a, sigmoid))
print("Prueba final: ", neural_network(X, ReLu))

Prueba inicial:  [[0.69269553]]
Prueba final:  [[1.2901751e+00]
 [3.9827325e-01]
 [7.5763340e+00]
 [8.4233580e+00]
 [5.8520720e+00]
 [6.1724410e-01]
 [7.7977270e+00]
 [1.6403930e+02]
 [7.7289650e+00]
 [1.0551858e+03]]
